yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='create_post'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetView,
    PasswordResetDoneView,
)
from django.urls import path, reverse_lazy

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done'),
        ),
        name='password_change_form',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset_form',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_comlete.html',
        ),
        name='password_reset_comlete',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
        ),
        name='password_reset_confirm',
    ),
    path(
        'signup/',
        SignUp.as_view(),
        name='signup',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == "about:author" %}active{% endif %}"
            href="{% url "about:author" %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == "about:tech" %}active{% endif %}"
            href="{% url "about:tech" %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            {% with request.resolver_match.kwargs.username as username %}
              <a
                class="nav-link {% if view_name == "posts:profile" and username == user.username %}active{% endif %}"
                href="{% url "posts:profile" user.username %}">
                Мои записи
              </a>
            {% endwith %}
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == "posts:create" %}active{% endif %}"
              href="{% url "posts:create_post" %}">
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == "users:password_change_form" %}active{% endif %}"
              href="{% url "users:password_change_form" %}">
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url "users:logout" %}">
              Выйти
            </a>
          </li>
          <li class="navbar-text">
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == "users:login" %}active{% endif %}"
              href="{% url "users:login" %}">
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == "users:signup" %}active{% endif %}"
              href="{% url "users:signup" %}">
              Регистрация
            </a>
          </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>