yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='create_post'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Название группы',
        help_text='Введите название группы',
        error_messages={
            'max_lenght': 'Название группы не должно превышать 200 символов',
            'unique': 'Группа с таким названием уже существует',
        },
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальный идентификатор группы',
        help_text=(
            'Введите идентификатор, который будет частью URL страницы: '
            'допустимо использование латинских букв, символ тире '
            'и нижнее подчёркивание'
        ),
        error_messages={
            'unique': 'Группа с таким идентификатором уже существует',
        },
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text=(
            'Добавьте полное описание группы, чтобы вам было проще найти '
            'единомышленников'
        ),
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст публикации',
        help_text='Текст нового поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
        help_text='Выберите автора публикации',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа публикации',
        help_text='Группа, к которой будет относиться пост',
    )

    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации комментария',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        ordering = ('author',)
        constraints = [
            models.UniqueConstraint(
                name='unique_user_author',
                fields=['user', 'author'],
            ),
            models.CheckConstraint(
                name='prevent_self_follow',
                check=~models.Q(user=models.F('author')),
            ),
        ]

yatube/posts/forms.py
from django.forms import ModelForm, ValidationError

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

        def clean_text(self):
            data = self.cleaned_data['text']
            if data.replace(' ', '') == '':
                raise ValidationError('Вы должны написать сообщение!')
            return data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        def clean_text(self):
            data = self.cleaned_data['text']
            if data.replace(' ', '') == '':
                raise ValidationError('Вы должны написать комментарий!')
            return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginate_page


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all().select_related('author', 'group')
    page_obj = paginate_page(request, post_list)
    context = {'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all().select_related('author')
    page_obj = paginate_page(request, post_list)
    context = {'group': group, 'page_obj': page_obj}
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    post_list = author.posts.all().select_related('group')
    page_obj = paginate_page(request, post_list)
    context = {'author': author, 'following': following, 'page_obj': page_obj}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'comments': comments, 'form': form}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate_page(request, post_list)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data"
            {% if is_edit %}
              {% with request.resolver_match.kwargs.post_id as post_id %}
                action="{% url "posts:post_edit" post_id %}"
              {% endwith %}
            {% else %}
              action="{% url "posts:create_post" %}"
            {% endif %}>
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста
                <span class="required text-danger" >*</span>
              </label>
              {% load user_filters %}
              {{ form.text|addclass:"form-control" }}
              <small id="id_text-help" class="form-text text-muted">
                {% if is_edit %}
                  Отредактируйте текущий пост
                {% else %}
                  {{ form.text.help_text }}
                {% endif %}
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группа                  
              </label>
              <select name="group" class="form-control" id="id_group">
                {% for field in form.group %}
                  {{ field }}
                {% endfor %}
              </select>
              <small id="id_group-help" class="form-text text-muted">
                {{ form.group.help_text }}
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image">
                Добавить картинку
              </label>
              {{ form.image }}
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Избранные авторы{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <h1>Избранные авторы</h1>
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"j E Y" }}</li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.group %}
      <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaksbr }}</p>
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"j E Y" }}</li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"j E Y" }}</li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.group %}
      <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url "posts:group_list" post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url "posts:profile" post.author.username %}">
            все посты пользователя
          </a>
        </li>
        {% if post.author == user %}
          <li class="list-group-item">
            <a href="{% url "posts:post_edit" post.id %}">
              редактировать запись
            </a>
          </li>
        {% endif %}
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% load user_filters %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% include 'posts/includes/comments.html' with comments=comments %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ posts_count }}</h3>
    {% if author != request.user %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}"
          role="button">
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}"
            role="button">
            Подписаться
          </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>Автор: {{ author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"j E Y" }}</li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url "posts:post_detail" post.id %}">подробная информация</a>
    </article>
    {% if post.group %}
      <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}